# Generated by Django 4.1.3 on 2022-12-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0002_remove_label_tasks"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(to="labels.label"),
        ),
    ]
